version: "3.8"
services:
  php:
    build:
      context: ./
      dockerfile: ./dockerfile
    container_name: php-server
    restart: always
    ports:
      - 8080:80
    volumes: 
      - ./base:/var/www/html
volumes:
  html: {}